const a = {
    farmer_number: '124354',
    farmer_monkharit: true,
    farmer_sex: 'man',
    farmer_last_name: 'benzemame',
    farmer_first_name: 'seddik',
    farmer_birth_day: '22-06-2019',
    farmer_address: 'city abdelmoumen',
    farmer_tel: '0540055010',
    farmer_job: 'controleur gps',
    farmer_morabi_card: false,
    farmer_level_educ: 'univ',
    // mazra3a
    farm_name: 'mazraa mostakbal',
    farm_address: 'farm_address',
    farm_wilaya: '',
    farm_year_begin: '',
    farm_7ala: '',
    farm_position_people: 'far',
    farm_geran: 'me',
    farm_geran_level_edcu: 'univ',
    farm_takwin_tarbiyat_aranib: 'morabi',
    farm_takwin_tarbiyat_aranib_year: '2018',
    farm_takwin_tarbiyat_aranib_duree: '1',
    farm_number_employe: 5,
    // aranib
    arnab_solala: 'hajin',
    arnab_date_imtilak: '01-01-2019',
    arnab_imtilak_why: 'because is',
    arnab_number_mothers: 100,
    arnab_number_fathers: 50,
    arnab_mothers_prix: 40.0,
    arnab_fathers_prix: 30.0,
    arnab_amrad: 'tanafossiya',
    arnab_darwa_intaj: 50,
    arnab_date_tajdid_kati3: '13/01/2019',
    arnab_ratm_intaj: 'mokathaf',
    arnab_3omr_intaj: 5,
    arnab_naw3_talki7: 'tabi3i',
    arnab_3omr_fitam: 4,
    arnab_motawassit_intaj: 10,
    arnab_nissbat_wafayat: 'fawk5',
    // mo3idat tarbiya
    mo3idat_numbers_ambar: 2,
    mo3idat_missa7a_ambar: 100,
    mo3idat_gaz: 'yes',
    mo3idat_eau: 'yes',
    mo3idat_elect: 'yes',
    mo3idat_khazan_eau: 'yes',
    mo3idat_khazan_eau_si3a: 2000,
    mo3idat_madba7_wilaya: 'yes',
    mo3idat_mosta3mala_7arara_tahwiya: 'bla bla bla',
    mo3idat_akfass_total: 20,
    mo3idat_akfass_mothers: 10,
    mo3idat_akfass_fathers: 10,
    mo3idat_akfass_tassmin: 10,
    mo3idat_naw3_akfass: 'ma7ali',
    // tagdiya
    tagdiya_name_3ilaf: 'sim',
    tagdiya_3ilaf_mada_idafiya: 'yes',
    tagdiya_3ilaf_tarika_chiraa: 'massna3',
    tagdiya_3ilaf_prix: 1000.0,
    tagdiya_3ilaf_massa3ib: 'bo3d massafa',
    // ri3aya
    ri3aya_numbers_bayatira: 3,
    ri3aya_mantojat_saydalaniya: 'yes',
    ri3aya_mantojat_saydalaniya_no: 'bla bla bla',
    ri3aya_mantojat_saydalaniya_yes: 'bla bla bla',
    ri3aya_talki7: 'vhd1',
    ri3aya_talki7_prix: 12,
    ri3aya_adwiya_mosta3mala: 'bla bla bla',
    ri3aya_mo3akimat_mosta3mala: 'bla bla bla',
    ri3aya_tamtalik_i3timad_si7i: 'yes',
    // tasswik,
    tasswik_motawassit_wazn_bay3_arnab: 3.5,
    tasswik_kayfiyat_bay3: 'arnab',
    tasswik_prix_arnab_kg: 35.0,
    tasswik_ayna_yatim_bay3: 'dakhel ambar',
    tasswik_morakib_si7i_dab7: 'yes',
    tasswik_barnamaj_dab7: 'monadam',
    tasswik_zabon_raissi: 'souk',
    tasswik_rotab_mostahlikin: 'bla bla bla',
    tasswik_bay3_montadam_nafss_kamiya: 'yes',
    tasswik_numbers_bay3_montadam_nafss_kamiya: 100,
    tasswik_kayfiya_takhzin: 'madbo7',
    tasswik_modat_takhzin: 'motawassita',
    tasswik_machakil: 'thakafa_istihlak',
    tasswik_ishar_li_mantojk: 'yes',
    tasswik_ishar_li_mantojk_how: 'bla bla bla',
    tasswik_ishar_li_mantojk_radat_fi3l: 'la chaye',
}
